CDR config API 2.20 changes
frollous/frollo-android-sdk pull request #114
Opened 2022-09-22 21:23 UTC by VindhyaRajagopal

## The problem ##
[WA-3633](https://frollo.atlassian.net/browse/WA-3633)

## Checklist ##

Use the :white_check_mark: emoji for when it's been done; :no_entry: when it still needs work;
strikethrough when an item of the checklist does not apply to the changes.

* Is the destination branch correct & intended? :white_check_mark:
* Is the code synced to latest (if applicable)? :white_check_mark:
* Has the SDK example app build passed locally? :white_check_mark:
* Is the correct JIRA ticket referenced? :white_check_mark:
* Is the correct API docs/Confluence Page referenced? :white_check_mark:
* Have all the AC's in the ticket passed? :white_check_mark:
* Have you followed proper naming conventions in the code? :white_check_mark:
* Has the code been properly covered with unit & android tests?NA
* Have the full test suite (unit & android tests) passed locally?NA
* Has the changelog.md, packages.md, overview.md, extras.md been updated? :white_check_mark:
* Has the dokka task passed?NA
* Have you committed database schema changes (if applicable)? :white_check_mark:

2022-09-22 23:43 UTC, hailefrollo approved these changes

2022-09-26 00:09 UTC, deepakmn86 requested changes

2022-09-26 00:09 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
> +        cdrConfigExternalId: String? = null,
Actually i forgot why we added this. I didn't find this query parameter in the API documentation

2022-09-26 00:09 UTC, deepakmn86 commented on changelog.md
> +- Add field in ConsentResponse & request
this should be part of 3.19 changes only below.

2022-09-27 01:27 UTC, deepakmn86 requested changes

2022-09-27 01:27 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
>                  // END - Add column initial_sync_window_weeks
delete above 3

2022-09-27 01:27 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                // START - Drop column adr_id, adr_name and add software_id, software_name, summary, description
```
// START - Drop columns adr_id, adr_name and Add columns initial_sync_window_weeks,
// additional_permissions, software_id, software_name, summary, image_url, description
```

2022-09-27 01:27 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                // End - Drop column adr_id, adr_name and add software_id, software_name, summary, description
```
// END - Drop columns adr_id, adr_name and Add columns initial_sync_window_weeks,
// additional_permissions, software_id, software_name, summary, image_url, description
```

2022-09-27 01:27 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                database.execSQL("INSERT INTO cdr_configuration(config_id, support_email, sharing_durations, permissions, additional_permissions, external_id, display_name, cdr_policy_url, model, rel
as original table doesn't have these new columns we cannot have these columns in the insert command. and also we have to insert from original table to the newly created table.

```
database.execSQL("INSERT INTO cdr_configuration(config_id, support_email, sharing_durations, permissions, external_id, display_name, cdr_policy_url, model, related_parties, sharing_use_duration) SELECT config_id, support_email, sharing_durations, permissions, external_id, display_name, cdr_policy_url, model, related_parties, sharing_use_duration FROM original_cdr_configuration")
```

2022-09-27 02:17 UTC, deepakmn86 approved these changes

2022-09-27 02:38 UTC, merged