WA-4090 Cashflow reports API changes
frollous/frollo-android-sdk pull request #150
Opened 2022-11-16 04:47 UTC by VindhyaRajagopal

## The problem ##

[WA-4090](https://frollo.atlassian.net/browse/WA-4090)
[ Doc Reference](https://frollo.atlassian.net/wiki/spaces/DEV/pages/3030908999/Cashflow+Reports+API+Money+In+Money+Out+-+Credit+Debit)

## The solution ##

## Checklist ##

Use the :white_check_mark: emoji for when it's been done; :no_entry: when it still needs work;
strikethrough when an item of the checklist does not apply to the changes.

* Is the destination branch correct & intended?:white_check_mark:
* Is the code synced to latest (if applicable)?:white_check_mark:
* Has the SDK example app build passed locally?:white_check_mark:
* Is the correct JIRA ticket referenced?:white_check_mark:
* Is the correct API docs/Confluence Page referenced?
* Have all the AC's in the ticket passed?:white_check_mark:
* Have you followed proper naming conventions in the code?:white_check_mark:
* Has the code been properly covered with unit & android tests?
* Have the full test suite (unit & android tests) passed locally?
* Has the changelog.md, packages.md, overview.md, extras.md been updated?:white_check_mark:
* Has the dokka task passed?NA
* Have you committed database schema changes (if applicable)?NA

## Results ##

<img src="https://user-images.githubusercontent.com/64941838/202085965-9b0fc592-2a2c-4631-ab3a-48cec83db7ff.png" width="200">

2022-11-16 07:15 UTC, deepakmn86 requested changes

2022-11-16 07:15 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt
> +     * Fetch tag reports from the host
cashflow reports

2022-11-16 07:15 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt
> +     * @param fromDate Start date in the format yyyy-MM-dd to fetch reports from (inclusive). See [Report.DATE_FORMAT_PATTERN]
CashflowReport. DATE_FORMAT_PATTERN

2022-11-16 07:15 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt
> +     * @param toDate End date in the format yyyy-MM-dd to fetch reports up to (inclusive). See [Report.DATE_FORMAT_PATTERN]
CashflowReport. DATE_FORMAT_PATTERN

2022-11-16 07:15 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt
> +        period: TransactionReportPeriod,
are these parameters optional or all are required?

2022-11-16 07:15 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt
> +                    response?.toCashflowReports()
you can just do `response.data`

2022-11-16 07:15 UTC, deepakmn86 commented on src/sharedTest/kotlin/us/frollo/frollosdk/model/TestCashflowReportData.kt
> +class TestCashflowReportData
do we need this?

2022-11-16 07:15 UTC, deepakmn86 commented on src/test/kotlin/us/frollo/frollosdk/mapping/ReportsMappingTest.kt
> +    fun testCashflowReportResponseToCashflowReport() {
not needed if we remove the mapping function itself

2022-11-16 07:15 UTC, deepakmn86 commented on src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataReport.kt
> +internal fun testCashflowReportResponseData(): CashflowReportResponse {
not needed if we remove the mapping function itself?

2022-11-16 22:51 UTC, VindhyaRajagopal commented on src/main/kotlin/us/frollo/frollosdk/model/coredata/reports/CashflowReport.kt
> +    @SerializedName("balance")val balance: String
All these are required as per doc.
<img width="1728" alt="Screen Shot 2022-11-14 at 12 05 40 pm" src="https://user-images.githubusercontent.com/64941838/202311361-60cd3f0e-eea3-4eb1-a38c-bb282c7f9bed.png">

2022-11-17 05:02 UTC, deepakmn86 approved these changes

2022-11-17 05:02 UTC, merged