WA-4428: SDK - Create manual transactions
frollous/frollo-android-sdk pull request #183
Opened 2023-03-27 03:40 UTC by wgkeller

## The problem ##

As per: 

WA-4428

Points addressed:
* Added new request types
* Created new test case
* Created new API endpoint for POST 
* Cleaned up gradle files to make project build locally without including into parent project

2023-03-27 22:45 UTC, VindhyaRajagopal commented on .gitignore
> +
Extra line can be removed?

2023-03-27 22:52 UTC, wgkeller commented on .gitignore
> +
Yes. Done.

2023-03-28 01:33 UTC, VindhyaRajagopal requested changes

2023-03-28 01:33 UTC, VindhyaRajagopal commented on .gitignore
> +schemas/
Can we update overview.md & packages.md(for added packages like TransactionType)?

2023-03-28 02:07 UTC, wgkeller commented on .gitignore
> +schemas/
Updated overview.md but there are no new packages created, only new types in existing packages

2023-03-28 02:29 UTC, VindhyaRajagopal approved these changes

2023-03-28 02:31 UTC, merged