Feature/wa 4771
frollous/frollo-android-sdk pull request #198
Opened 2023-07-27 02:56 UTC by wgkeller

## The problem ##

WA-4771:
* Remove local database for transactions
* Implement suspended (coroutine) functions to support API requests
* Upgrade database from v23 -> v24

## The solution ##

What's the technical solution?
* Continued suspended functions for linear style coding for async operations

2023-07-27 22:38 UTC, VindhyaRajagopal requested changes

2023-07-27 22:38 UTC, VindhyaRajagopal commented on src/androidTest/kotlin/us/frollo/frollosdk/network/NetworkHelperTest.kt
> -    @Test
@wgkeller Why is this test removed? Was this causing any issues

2023-07-27 22:38 UTC, VindhyaRajagopal commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                    MIGRATION_22_23,
MIGRATION_22_23 added twice

2023-07-27 22:38 UTC, VindhyaRajagopal commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                database.execSQL("DROP TABLE transaction_model")
Do we have to do "DROP INDEX IF EXISTS" of `transaction_model` table explicitly before dropping the table?

2023-07-27 22:43 UTC, VindhyaRajagopal requested changes

2023-07-27 22:43 UTC, VindhyaRajagopal commented on gradle.properties
> +org.gradle.daemon=false
Also, please bump the SDK version to 3.25.0.
And, add these changes summary in changelog.md file for 3.25.0 release.

2023-07-27 23:05 UTC, wgkeller commented on src/androidTest/kotlin/us/frollo/frollosdk/network/NetworkHelperTest.kt
> -    @Test
A field was removed from NetworkHelper (userAgent) - which is no longer required. As per code comments:
` // "us.frollo.frollosdk|SDK1.0.0|B777|Android8.1.0|API2.0"
    @Deprecated("Not needed anymore by the Host on v2 APIs")
    internal val userAgent: String
        get() = "${BuildConfig.LIBRARY_PACKAGE_NAME}|SDK${BuildConfig.SDK_VERSION_NAME}|B${BuildConfig.SDK_VERSION_CODE}|Android${Build.VERSION.RELEASE}|API$API_VERSION"
`

2023-07-27 23:06 UTC, wgkeller commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                    MIGRATION_22_23,
Merge issue, I'll fix

2023-07-28 00:04 UTC, wgkeller commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                database.execSQL("DROP TABLE transaction_model")
Fixed with latest commit

2023-07-28 00:04 UTC, wgkeller commented on src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
> +                    MIGRATION_22_23,
Fixed with latest commit

2023-07-28 00:05 UTC, wgkeller commented on gradle.properties
> +org.gradle.daemon=false
Fixed with latest commit

2023-07-28 01:24 UTC, VindhyaRajagopal approved these changes

2023-07-28 06:26 UTC, merged