Feature/sdk 662 add statements
frollous/frollo-android-sdk pull request #52
Opened 2021-08-13 14:31 UTC by kfrollo

2021-08-13 14:33 UTC, kfrollo commented
![Uploading Screen Shot 2021-08-14 at 12.27.51 am.png…]()

2021-08-13 14:38 UTC, kfrollo commented
Files to review 
import us.frollo.frollosdk.model.api.statements.Statement
import us.frollo.frollosdk.model.api.statements.StatementResponse
import us.frollo.frollosdk.model.api.statements.StatementSortBy
import us.frollo.frollosdk.model.api.statements.StatementType
import us.frollo.frollosdk.model.coredata.shared.OrderType
import us.frollo.frollosdk.network.NetworkService
import us.frollo.frollosdk.network.api.StatementsAPI
us.frollo.frollosdk.statements.Statements

@deepakmn86 talk to me before u start this

2021-08-16 01:55 UTC, deepakmn86 requested changes

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/Statement.kt
> +    @SerializedName("issued_date") val issuedDate: String? // 2021-01-01
can you change the commented date to `// yyyy-MM-dd`

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/StatementResponse.kt
> +internal data class StatementResponse(
This is not needed. You can use `PaginatedResponse` check ManagedProductsAPI

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/StatementSortBy.kt
> +enum class StatementSortBy {
add documentation comments for this class and for each enum inside.

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/StatementSortBy.kt
> +enum class StatementSortBy {
also use @Keep

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/StatementType.kt
> +enum class StatementType {
add documentation comments for this class and for each enum inside.

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/network/api/StatementsAPI.kt
> +        @Query("account_ids")accountIds: String,
Use `@QueryMap options: Map<String, String>` and create an extn function in APIExtension.kt
You can refer to the methods in APIExtension.kt for how we have done for other APIs with query parameters in the request.

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +/** Manages all aspects of Addresses */
`Manages all aspects of Statements`

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +     * Refresh statements list from host
`Fetch list of statements from host`

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +     */
please fix documentation comments for each parameter. Refer to any existing methods in SDK in any other feature.

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +        completion: OnFrolloSDKCompletionListener<PaginatedResultWithData<PaginationInfo, List<Statement>>>? = null
completion listner cannot be nullable here

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +            before, after, size, sortBy, orderType
here can you please do like below to ensure we are assigning the correct values to each parameter.
```
accountIds = accountIds,
statementType = statementType,
...etc
```

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +            accountIds.joinToString(","), statementType, fromDate, toDate,
do the `joinToString` inside APIExtension function

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +                    Log.e("$TAG#fetchManagedProducts", resource.error?.localizedDescription)
`$TAG#fetchStatements`

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +        completion: OnFrolloSDKCompletionListener<PaginatedResultWithData<PaginationInfo, List<Statement>>>?
completion listener cannot be nullable here

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +     * @return Single<InputStream> inputStream of file
@param completion: Completion handler with optional error if the request fails and statement PDF body if succeeds

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +    fun fetchStatement(referenceId: String, completion: OnFrolloSDKCompletionListener<Resource<ResponseBody>?>? = null) {
completion listener should not be nullable. and you can remove both question marks

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +                    Log.e("$TAG#downloadStatement", resource.error?.localizedDescription)
`$TAG#fetchStatement`

2021-08-16 01:55 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/statements/Statement.kt
> +)
create a companion object here to define the date pattern.
```
companion object {
    /** Date format for dates associated with Statement */
    const val DATE_FORMAT_PATTERN = "yyyy-MM-dd"
}
```

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +    fun testRefreshStatements() {
`testFetchStatements `

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +        val requestPath = "statements?account_ids=1"
provide full parameters list in request so that we are testing the request as well.

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +
add
```
assertEquals(Resource.Status.SUCCESS, resource.status)
assertNull(resource.error)
```

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +    fun testRefreshStatementFailsIfLoggedOut() {
`testFetchStatementsFailsIfLoggedOut`

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +        tearDown()
write tests for `fetchStatement` & `testFetchStatementFailsIfLoggedOut`
refer to ResponseDataTest

2021-08-16 01:55 UTC, deepakmn86 commented on src/androidTest/res/raw/statements_invalid.json
> +{
we can remove this file i guess as we don't have any tests for invalid scenario

2021-08-16 02:10 UTC, deepakmn86 requested changes

2021-08-16 02:10 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +class StatementsTest : BaseAndroidTest() {
- Add `statements` in FrolloSDK.kt
- Add Statements under Features in changelog.md

2021-08-16 06:49 UTC, deepakmn86 requested changes

2021-08-16 06:49 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/BaseAndroidTest.kt
> +import us.frollo.frollosdk.statements.Statements
run dokka gradle task

2021-08-16 07:13 UTC, kfrollo commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +        tearDown()
no testFetchStatementFailsIfLoggedOut in ResponseDataTest

2021-08-16 07:15 UTC, kfrollo commented on src/androidTest/kotlin/us/frollo/frollosdk/statements/StatementsTest.kt
> +
not really a resource
PaginatedResultWithData.Success<PaginationInfo, List<Statement>>

2021-08-16 11:24 UTC, deepakmn86 requested changes

2021-08-16 11:24 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +     * @param fromDate start date of statement format yyyy-MM-dd (optional)
`@param fromDate start date of statement format yyyy-MM-dd (optional). Please use [Statement.DATE_FORMAT_PATTERN] for the format pattern.`

2021-08-16 11:24 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +     * @param toDate end date of statement format yyyy-MM-dd (optional),//2021-01-01(optional)
`@param toDate end date of statement format yyyy-MM-dd (optional). Please use [Statement.DATE_FORMAT_PATTERN] for the format pattern.`

2021-08-16 11:24 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/statements/Statements.kt
> +    fun fetchStatement(referenceId: String, completion: OnFrolloSDKCompletionListener<Resource<ResponseBody>?>) {
You can remove `?` as `Resource` should never be null.

2021-08-16 22:27 UTC, deepakmn86 approved these changes

2021-08-16 22:27 UTC, merged