feature/SDK-697-add-financial-passport-apis
frollous/frollo-android-sdk pull request #67
Opened 2021-11-16 01:54 UTC by kfrollo

## The problem ##

(https://frollo.atlassian.net/browse/SDK-697)

## The solution ##

na

## Checklist ##

Use the :white_check_mark: emoji for when it's been done; :no_entry: when it still needs work;
strikethrough when an item of the checklist does not apply to the changes.

* Is the destination branch correct & intended? :white_check_mark: 
* Is the code synced to latest (if applicable)? :white_check_mark: 
* Has the SDK example app build passed locally? :white_check_mark: 
* Is the correct JIRA ticket referenced? :white_check_mark: 
* Is the correct API docs/Confluence Page referenced? :white_check_mark: 
* Have all the AC's in the ticket passed? :white_check_mark: 
* Have you followed proper naming conventions in the code? :white_check_mark: 
* Has the code been properly covered with unit & android tests? :white_check_mark: 
* Have the full test suite (unit & android tests) passed locally? :white_check_mark: 
* Has the changelog.md, packages.md, overview.md, extras.md been updated?
* Has the dokka task passed? :white_check_mark: 
* Have you commited database schema changes (if applicable)? :white_check_mark: 

## Results ##

Add screenshots / videos.
Note: After you upload the file, you can resize it using the format 

<img src="" width="200">

2021-11-16 03:58 UTC, deepakmn86 requested changes

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/IncomeExpensesBreakdown.kt
> +data class IncomeExpensesBreakdown(
All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Income.kt
> +data class Income(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Income.kt
> +data class Income(
- rename as `FPIncomeExpense`
- Delete `Expense` file as we can reuse this

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Income.kt
> +data class Income(
- Change all Double to BigDecimal
- All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Income.kt
> +    @SerializedName("breakdown") val breakdown: List<IncomeExpensesBreakdown>
we also need `averages` as per documentation

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Expenses.kt
> +data class Expenses(
delete this file as we can reuse `FPIncomeExpense`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Category.kt
> +data class Category(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Category.kt
> +data class Category(
rename as `FPIncomeExpenseBreakdownCategory`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Category.kt
> +data class Category(
All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Averages.kt
> +data class Averages(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Averages.kt
> +data class Averages(
rename as `FPIncomeExpenseAverages`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Averages.kt
> +data class Averages(
- Change all Double to BigDecimal
- All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesBreakdown.kt
> +data class AssetsLiabilitiesBreakdown(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesBreakdown.kt
> +data class AssetsLiabilitiesBreakdown(
rename as `FPAssetLiabilityBreakdown`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesBreakdown.kt
> +data class AssetsLiabilitiesBreakdown(
- Closing Balance should be BigDecimal
- All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesAccounts.kt
> +data class AssetsLiabilitiesAccounts(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesAccounts.kt
> +data class AssetsLiabilitiesAccounts(
rename as `FPAssetLiabilityBreakdownAccount`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesAccounts.kt
> +data class AssetsLiabilitiesAccounts(
- Change all Double to BigDecimal
- All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/AssetsLiabilitiesAccounts.kt
> +    @SerializedName("name") val name: String,
add `number` and `bsb` as well as per documentation

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Assets.kt
> +data class Assets(
delete this file as we can reuse `FPAssetLiability`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Accounts.kt
> +data class Accounts(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Accounts.kt
> +data class Accounts(
rename as `FPAccount`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Accounts.kt
> +data class Accounts(
remove `_` from member names and capitalize the first letter of the words in the names

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Accounts.kt
> +    @SerializedName("account_name") val account_name: String,
add `account_number` and `bsb` as per documentation

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Accounts.kt
> +data class Accounts(
- Change all Double to BigDecimal
- All members must be nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/FinancialPassportResponse.kt
> +    @SerializedName("to_date") val to_date: String,
everything below this are nullable

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/FinancialPassportResponse.kt
> +data class FinancialPassportResponse(
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/ExportType.kt
> +enum class ExportType {
add documentation for the class and also for each member. refer to iOS PR.

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/ExportType.kt
> +enum class ExportType {
add `@Keep` annotation

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +     * @param aggregator: `Provider.AggregatorType` type; Optional
`[AggregatorType]`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +     * @param completion: Completion handler with optional error if the request fails and list of [Statement] with pagination information if succeeds
Completion handler with optional error if the request fails or [FinancialPassportResponse] if succeeds

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/FinancialPassportResponse.kt
> +    @SerializedName("risk_scores") val risk_scores: List<RiskScores>
add a companion object to define the date format associated with financial passport. refer to `BillPayment` model

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +     * @param fromDate: From date of financial passport; Optional; defaults to one year ago
add at the end `. See [FinancialPassportResponse.DATE_FORMAT_PATTERN]`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +     * @param toDate: To date of financial passport; Optional; defaults to today
add at the end `. See [FinancialPassportResponse.DATE_FORMAT_PATTERN]`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +    private val financialPassport: FinancialPassportAPI = network.create(FinancialPassportAPI::class.java)
`affordabilityAPI: AffordabilityAPI`

2021-11-16 03:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/financialpassport/Affordability.kt
> +     * @param completion: Completion handler with optional error if the request fails and statement PDF body if succeeds
Completion handler with optional error if the request fails or Financial Passport PDF body if succeeds

2021-11-16 03:58 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/financialpassport/AffordabilityTest.kt
> +            assertEquals("Loans", model?.liabilities?.breakdown?.get(0)?.name)
compare a few bigdecimal values

2021-11-16 03:58 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/financialpassport/AffordabilityTest.kt
> +                    if (request.trimmedPath == "affordability/financialpassport") {
instead of `"affordability/financialpassport"` you can do `AffordabilityAPI.<url variable>`

2021-11-16 03:58 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/financialpassport/AffordabilityTest.kt
> +        assertEquals("affordability/financialpassport", request.trimmedPath)
instead of `"affordability/financialpassport"` you can do `AffordabilityAPI.<url variable>`

2021-11-16 03:58 UTC, deepakmn86 commented on src/androidTest/kotlin/us/frollo/frollosdk/financialpassport/AffordabilityTest.kt
> +
write tests for

`testFinancialPassportExport`
`testFinancialPassportExportFailsIfLoggedOut`

refer to statement tests

2021-11-16 07:04 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Totals.kt
> +data class Totals(
They are string, bad on my part

2021-11-16 07:04 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/SummaryTotals.kt
> +data class SummaryTotals(
They are string, bad on my part

2021-11-16 07:07 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/RiskScores.kt
> +data class RiskScores(
They are string, bad on my part

2021-11-16 07:09 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Liabilities.kt
> +data class Liabilities(
String, same reason

2021-11-16 07:14 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/financialpassport/Averages.kt
> +data class Averages(
String

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpenseBreakdownTotals.kt
> +data class FPIncomeExpenseBreakdownTotals(
also add documentation for the class itself.
```
/** Data representation of the breakdown totals of the Financial Passport's Income and Expense Totals */
```

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPSummaryTotals.kt
> +data class FPSummaryTotals(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/AssetsLiabilities.kt
> +data class AssetsLiabilities(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpensesBreakdown.kt
> +data class FPIncomeExpensesBreakdown(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpensesBreakdown.kt
> +    /**  The date of the first Transaction in this breakdown; Optional */
add at the end `. See [FinancialPassportResponse.DATE_FORMAT_PATTERN]`

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpensesBreakdown.kt
> +    /**  The date of the last Transaction in this breakdown; Optional */
add at the end `. See [FinancialPassportResponse.DATE_FORMAT_PATTERN]`

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpenseBreakdownCategory.kt
> +data class FPIncomeExpenseBreakdownCategory(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPIncomeExpenseAverages.kt
> +data class FPIncomeExpenseAverages(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetLiabilityBreakdown.kt
> +data class FPAssetLiabilityBreakdown(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetLiabilityBreakdown.kt
> +    @SerializedName("accounts") val accounts: List<FPAssetsLiabilitiesBreakdownAccounts>
nullable

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetsLiabilitiesBreakdownAccounts.kt
> +data class FPAssetsLiabilitiesBreakdownAccounts(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetsLiabilitiesBreakdownAccounts.kt
> +    @SerializedName("id") val id: Int?,
`Long?`

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAccounts.kt
> +    @SerializedName("account_id") val accountId: Int?,
`Long?`

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAccounts.kt
> +data class FPAccounts(
also add documentation for the class itself.

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAccounts.kt
> +    @SerializedName("number") val number: String?
i think here its `account_number` as per doc

2021-11-16 08:58 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/affordability/Affordability.kt
> +    private val affordability: AffordabilityAPI = network.create(AffordabilityAPI::class.java)
`affordabilityAPI: AffordabilityAPI`

2021-11-16 11:53 UTC, kfrollo commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetsLiabilitiesBreakdownAccounts.kt
> +    @SerializedName("id") val id: Int?,
I think i already did this before

2021-11-16 23:51 UTC, deepakmn86 requested changes

2021-11-16 23:51 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/AssetsLiabilities.kt
> +data class AssetsLiabilities(
rename as `FPAssetLiability`

2021-11-16 23:51 UTC, deepakmn86 commented on src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetLiabilityBreakdown.kt
> +    @SerializedName("percentage") val percentage: BigDecimal?,
let percentage be a `Double` as its not money.

2021-11-17 00:07 UTC, deepakmn86 requested changes

2021-11-17 00:07 UTC, deepakmn86 commented on changelog.md
> +- Financial Passport
I have modified this file. please pull latest develop and resolve conflict. Move this one under the 3.12.0 section

2021-11-17 01:23 UTC, deepakmn86 approved these changes

2021-11-17 01:24 UTC, merged